name: Dev - Firebase Deploy
on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        env:
          CI: true
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P prod --only hosting
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
